### ISSUE TITLE
[BUG] UNABLE TO LOAD PANEL NETWORK

### ISSUE THREAD

**Issue by CanaryTours** [Guilouz/KlipperScreen-Flsun-Speeder-Pad#44]
My IP in the printer is changing every certain time (not sure why but is not a problem) when I went to the pad and press network to see the new IP I received an error called "unable to load panel network", I found the IP in the System screen but Mainsail wasn't loading, after 15-20 minutes with the printer on suddenly Mainsail worked, but the wifi screen in the pad is still the same, this was before the last update, never had this problem before, I just turned on the printer and received this error.

I just expected to see the wifi panel.

![photo_2024-06-04_09-14-29](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/62757735/b6290d55-85f1-4a48-8aec-a86f2edda12e)
![photo_2024-06-04_09-14-33](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/assets/62757735/45563f7b-1fc5-4f54-b513-7586ce37e8f9)

[KlipperScreen.log](https://github.com/user-attachments/files/15545131/KlipperScreen.log)

**Comment by Guilouz** [comment]
There is changes in lastest klipperscreen version it now use sdbus and networkmanager.
You need to restore pad and follow the new install process.

**Comment by CanaryTours** [comment]
So do i need to reinstall Klipper from the start? Not a problem, just to clarify

**Comment by Guilouz** [comment]
Yes

**Comment by RolexColocat** [comment]
I have the same problem. Network panel  shows this error and crashed KlipperScreen, however a complete reinstallation is not possible because during the installation process I get the error:
```
ERROR: Command errored out with exit status 1:
     command: /home/pi/.KlipperScreen-env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hj0a53ez/sdbus/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hj0a53ez/sdbus/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-hj0a53ez/sdbus/pip-egg-info
         cwd: /tmp/pip-install-hj0a53ez/sdbus/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hj0a53ez/sdbus/setup.py", line 46, in <module>
        systemd_version = get_libsystemd_version()
      File "/tmp/pip-install-hj0a53ez/sdbus/setup.py", line 33, in get_libsystemd_version
        process = subprocess_run(
      File "/usr/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '('pkg-config', '--modversion', 'libsystemd')' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error: pip install exited with status code 0
```

and of course:
```
Collecting sdbus==0.11.1 (from -r /home/pi/KlipperScreen/scripts/KlipperScreen-requirements.txt (line 3))
  Using cached sdbus-0.11.1.tar.gz (74 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
```

If I try to install (as indicated in README.md) with using file:  KlipperScreen-install-fix.sh  but this file is deleted?

```
pi@speeder-pad:~$ ./KlipperScreen/scripts/KlipperScreen-install-fix.sh
-bash: ./KlipperScreen/scripts/KlipperScreen-install-fix.sh: No such file or directory
pi@speeder-pad:~$ 
```

if I use file KlipperScreen-install.sh     (without 'fix' prefix) I see  same error with "sdbus".

What am I doing wrong?

**Comment by RolexColocat** [comment]
I have the same problem. Network panel shows this error and crashed KlipperScreen, however a complete reinstallation is not possible because during the installation process I get the error:

```
ERROR: Command errored out with exit status 1:
     command: /home/pi/.KlipperScreen-env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hj0a53ez/sdbus/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hj0a53ez/sdbus/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-hj0a53ez/sdbus/pip-egg-info
         cwd: /tmp/pip-install-hj0a53ez/sdbus/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hj0a53ez/sdbus/setup.py", line 46, in <module>
        systemd_version = get_libsystemd_version()
      File "/tmp/pip-install-hj0a53ez/sdbus/setup.py", line 33, in get_libsystemd_version
        process = subprocess_run(
      File "/usr/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '('pkg-config', '--modversion', 'libsystemd')' returned non-zero exit status 1.
    ----------------------------------------

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error: pip install exited with status code 0
```

and of course:

```
Collecting sdbus==0.11.1 (from -r /home/pi/KlipperScreen/scripts/KlipperScreen-requirements.txt (line 3))
  Using cached sdbus-0.11.1.tar.gz (74 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
```
If I try to install (as indicated in README.md) with using file: KlipperScreen-install-fix.sh but this file is deleted?

```
pi@speeder-pad:~$ ./KlipperScreen/scripts/KlipperScreen-install-fix.sh
-bash: ./KlipperScreen/scripts/KlipperScreen-install-fix.sh: No such file or directory
pi@speeder-pad:~$ 
```
if I use file KlipperScreen-install.sh (without 'fix' prefix) I see same error with "sdbus".

What am I doing wrong?

**Comment by tokamac** [comment]
What must be reinstalled, Klipper or KlipperScreen? 
How are we supposed to reinstall the software as Wi-Fi does not work anymore therefore the printer is inaccessible through SSH?
—
EDIT: Ok, I restored the whole "OS Image File" using on an SD card, meaning I have lost ALL my settings patiently tuned for months. 
I've been there since 3 hours, proceeding carefully according to the wiki. It will take the whole day to install, then days to set up the printer correctly again.
Speaking of destroying your means of production at the touch of an update!

**Comment by tokamac** [comment]
It took me the whole day (due to many errors). I finally managed to make the OS work again from scratch, but the current procedure lacks several steps to prevent pitfalls due to recent changes in Ubuntu.

In the section **Update dependencies**
after the command 
`curl -L https://raw.githubusercontent.com/Guilouz/Klipper-Flsun-Speeder-Pad/main/Downloads/sp_installer2.sh -o /home/pi/sp_installer2.sh`
and just before the last one, enter:
`sudo apt install python3-testresources`

then instead of 
`sudo bash /home/pi/sp_installer2.sh`
type
`sudo bash /home/pi/sp_installer2.sh --use-deprecated=legacy-resolver`

then also enter
`pip install -U packaging`
which installs `packaging>=24` (lower versions like v20 won't work due to an incompatibility with latest setuptools). Problem is if packaging is already installed (it is) it won't update by itself!

When launching kiauh for the first time, _DO NOT select the brand new version 6_ (currently in alpha), it doesn't work! Worse: when the prompt invites you to test v6, if you accept and select 'remember my choice next time', there's no way back! When doing so, it's over, you're stuck. If you did it, you can now erase the whole OS with the SD card and start over again.
